#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-function"
#endif
// Autogenerated with StateSmith 0.21.0-alpha-1+7e3f96c13426722a35ad6604c427da48d8538e48.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#include "Autotext.h"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(Autotext* sm, Autotext_StateId desired_state);

static void ROOT_enter(Autotext* sm);

static void ACCUMULATING_enter(Autotext* sm);

static void ACCUMULATING_exit(Autotext* sm);

static void ACCUMULATING_on_break_match(Autotext* sm);

static void ACCUMULATING_on_extend_match(Autotext* sm);

static void ACCUMULATING_on_full_match(Autotext* sm);

static void IDLE_enter(Autotext* sm);

static void IDLE_exit(Autotext* sm);

static void IDLE_on_first_match_char(Autotext* sm);

static void IDLE_on_non_match_char(Autotext* sm);


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void Autotext_ctor(Autotext* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void Autotext_start(Autotext* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: TransitionTo(idle)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `idle`.
            IDLE_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void Autotext_dispatch_event(Autotext* sm, Autotext_EventId event_id)
{
    switch (sm->state_id)
    {
        // STATE: Autotext
        case Autotext_StateId_ROOT:
            // No events handled by this state (or its ancestors).
            break;
        
        // STATE: accumulating
        case Autotext_StateId_ACCUMULATING:
            switch (event_id)
            {
                case Autotext_EventId_ON_EXTEND_MATCH: ACCUMULATING_on_extend_match(sm); break;
                case Autotext_EventId_ON_FULL_MATCH: ACCUMULATING_on_full_match(sm); break;
                case Autotext_EventId_ON_BREAK_MATCH: ACCUMULATING_on_break_match(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: idle
        case Autotext_StateId_IDLE:
            switch (event_id)
            {
                case Autotext_EventId_ON_FIRST_MATCH_CHAR: IDLE_on_first_match_char(sm); break;
                case Autotext_EventId_ON_NON_MATCH_CHAR: IDLE_on_non_match_char(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
    }
    
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(Autotext* sm, Autotext_StateId desired_state)
{
    while (sm->state_id != desired_state)
    {
        switch (sm->state_id)
        {
            case Autotext_StateId_ACCUMULATING: ACCUMULATING_exit(sm); break;
            
            case Autotext_StateId_IDLE: IDLE_exit(sm); break;
            
            default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
        }
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(Autotext* sm)
{
    sm->state_id = Autotext_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ACCUMULATING
////////////////////////////////////////////////////////////////////////////////

static void ACCUMULATING_enter(Autotext* sm)
{
    sm->state_id = Autotext_StateId_ACCUMULATING;
}

static void ACCUMULATING_exit(Autotext* sm)
{
    sm->state_id = Autotext_StateId_ROOT;
}

static void ACCUMULATING_on_break_match(Autotext* sm)
{
    // accumulating behavior
    // uml: on_break_match TransitionTo(idle)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        ACCUMULATING_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `idle`.
        IDLE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for accumulating
    
    // No ancestor handles this event.
}

static void ACCUMULATING_on_extend_match(Autotext* sm)
{
    // accumulating behavior
    // uml: on_extend_match TransitionTo(accumulating)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        ACCUMULATING_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `accumulating`.
        ACCUMULATING_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for accumulating
    
    // No ancestor handles this event.
}

static void ACCUMULATING_on_full_match(Autotext* sm)
{
    // accumulating behavior
    // uml: on_full_match TransitionTo(idle)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        ACCUMULATING_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `idle`.
        IDLE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for accumulating
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state IDLE
////////////////////////////////////////////////////////////////////////////////

static void IDLE_enter(Autotext* sm)
{
    sm->state_id = Autotext_StateId_IDLE;
}

static void IDLE_exit(Autotext* sm)
{
    sm->state_id = Autotext_StateId_ROOT;
}

static void IDLE_on_first_match_char(Autotext* sm)
{
    // idle behavior
    // uml: on_first_match_char TransitionTo(accumulating)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        IDLE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `accumulating`.
        ACCUMULATING_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for idle
    
    // No ancestor handles this event.
}

static void IDLE_on_non_match_char(Autotext* sm)
{
    // idle behavior
    // uml: on_non_match_char TransitionTo(idle)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        IDLE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `idle`.
        IDLE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for idle
    
    // No ancestor handles this event.
}

// Thread safe.
char const * Autotext_state_id_to_string(Autotext_StateId id)
{
    switch (id)
    {
        case Autotext_StateId_ROOT: return "ROOT";
        case Autotext_StateId_ACCUMULATING: return "ACCUMULATING";
        case Autotext_StateId_IDLE: return "IDLE";
        default: return "?";
    }
}

// Thread safe.
char const * Autotext_event_id_to_string(Autotext_EventId id)
{
    switch (id)
    {
        case Autotext_EventId_ON_BREAK_MATCH: return "ON_BREAK_MATCH";
        case Autotext_EventId_ON_EXTEND_MATCH: return "ON_EXTEND_MATCH";
        case Autotext_EventId_ON_FIRST_MATCH_CHAR: return "ON_FIRST_MATCH_CHAR";
        case Autotext_EventId_ON_FULL_MATCH: return "ON_FULL_MATCH";
        case Autotext_EventId_ON_NON_MATCH_CHAR: return "ON_NON_MATCH_CHAR";
        default: return "?";
    }
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif
