// Autogenerated with StateSmith 0.21.0-alpha-1+7e3f96c13426722a35ad6604c427da48d8538e48.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#pragma once  // You can also specify normal include guard. See https://github.com/StateSmith/StateSmith/blob/main/docs/settings.md
#include <stdint.h>

typedef enum Autotext_EventId
{
    Autotext_EventId_ON_BREAK_MATCH = 0,
    Autotext_EventId_ON_EXTEND_MATCH = 1,
    Autotext_EventId_ON_FIRST_MATCH_CHAR = 2,
    Autotext_EventId_ON_FULL_MATCH = 3,
    Autotext_EventId_ON_NON_MATCH_CHAR = 4
} Autotext_EventId;

enum
{
    Autotext_EventIdCount = 5
};

typedef enum Autotext_StateId
{
    Autotext_StateId_ROOT = 0,
    Autotext_StateId_ACCUMULATING = 1,
    Autotext_StateId_IDLE = 2
} Autotext_StateId;

enum
{
    Autotext_StateIdCount = 3
};


// Generated state machine
// forward declaration
typedef struct Autotext Autotext;

// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void Autotext_ctor(Autotext* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void Autotext_start(Autotext* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void Autotext_dispatch_event(Autotext* sm, Autotext_EventId event_id);

// Thread safe.
char const * Autotext_state_id_to_string(Autotext_StateId id);

// Thread safe.
char const * Autotext_event_id_to_string(Autotext_EventId id);

// Generated state machine
struct Autotext
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    Autotext_StateId state_id;
};

