// Autogenerated with StateSmith 0.21.0-alpha-1+7e3f96c13426722a35ad6604c427da48d8538e48.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#pragma once  // You can also specify normal include guard. See https://github.com/StateSmith/StateSmith/blob/main/docs/settings.md
#include <stdint.h>

typedef enum Holdseq_EventId
{
    Holdseq_EventId_ON_FIRST_SECONDARY = 0,
    Holdseq_EventId_ON_OTHER_KEY = 1,
    Holdseq_EventId_ON_PRIMARY_PRESS = 2,
    Holdseq_EventId_ON_PRIMARY_RELEASE = 3,
    Holdseq_EventId_ON_SECONDARY_PRESS = 4
} Holdseq_EventId;

enum
{
    Holdseq_EventIdCount = 5
};

typedef enum Holdseq_StateId
{
    Holdseq_StateId_ROOT = 0,
    Holdseq_StateId_COLLECTING = 1,
    Holdseq_StateId_IDLE = 2,
    Holdseq_StateId_PRIMARY_HELD = 3
} Holdseq_StateId;

enum
{
    Holdseq_StateIdCount = 4
};


// Generated state machine
// forward declaration
typedef struct Holdseq Holdseq;

// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void Holdseq_ctor(Holdseq* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void Holdseq_start(Holdseq* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void Holdseq_dispatch_event(Holdseq* sm, Holdseq_EventId event_id);

// Thread safe.
char const * Holdseq_state_id_to_string(Holdseq_StateId id);

// Thread safe.
char const * Holdseq_event_id_to_string(Holdseq_EventId id);

// Generated state machine
struct Holdseq
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    Holdseq_StateId state_id;
};

