// Autogenerated with StateSmith 0.21.0-alpha-1+7e3f96c13426722a35ad6604c427da48d8538e48.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#pragma once  // You can also specify normal include guard. See https://github.com/StateSmith/StateSmith/blob/main/docs/settings.md
#include <stdint.h>

typedef enum VimModal_EventId
{
    VimModal_EventId_ON_A = 0,
    VimModal_EventId_ON_COLON = 1,
    VimModal_EventId_ON_ENTER = 2,
    VimModal_EventId_ON_ESCAPE = 3,
    VimModal_EventId_ON_I = 4,
    VimModal_EventId_ON_O = 5,
    VimModal_EventId_ON_SHIFT_R = 6,
    VimModal_EventId_ON_V = 7
} VimModal_EventId;

enum
{
    VimModal_EventIdCount = 8
};

typedef enum VimModal_StateId
{
    VimModal_StateId_ROOT = 0,
    VimModal_StateId_COMMAND = 1,
    VimModal_StateId_INSERT = 2,
    VimModal_StateId_NORMAL = 3,
    VimModal_StateId_REPLACE = 4,
    VimModal_StateId_VISUAL = 5
} VimModal_StateId;

enum
{
    VimModal_StateIdCount = 6
};


// Generated state machine
// forward declaration
typedef struct VimModal VimModal;

// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void VimModal_ctor(VimModal* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void VimModal_start(VimModal* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void VimModal_dispatch_event(VimModal* sm, VimModal_EventId event_id);

// Thread safe.
char const * VimModal_state_id_to_string(VimModal_StateId id);

// Thread safe.
char const * VimModal_event_id_to_string(VimModal_EventId id);

// Generated state machine
struct VimModal
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    VimModal_StateId state_id;
};

