#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-function"
#endif
// Autogenerated with StateSmith 0.21.0-alpha-1+7e3f96c13426722a35ad6604c427da48d8538e48.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#include "VimModal.h"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(VimModal* sm, VimModal_StateId desired_state);

static void ROOT_enter(VimModal* sm);

static void COMMAND_enter(VimModal* sm);

static void COMMAND_exit(VimModal* sm);

static void COMMAND_on_enter(VimModal* sm);

static void COMMAND_on_escape(VimModal* sm);

static void INSERT_enter(VimModal* sm);

static void INSERT_exit(VimModal* sm);

static void INSERT_on_escape(VimModal* sm);

static void NORMAL_enter(VimModal* sm);

static void NORMAL_exit(VimModal* sm);

static void NORMAL_on_a(VimModal* sm);

static void NORMAL_on_colon(VimModal* sm);

static void NORMAL_on_i(VimModal* sm);

static void NORMAL_on_o(VimModal* sm);

static void NORMAL_on_shift_r(VimModal* sm);

static void NORMAL_on_v(VimModal* sm);

static void REPLACE_enter(VimModal* sm);

static void REPLACE_exit(VimModal* sm);

static void REPLACE_on_escape(VimModal* sm);

static void VISUAL_enter(VimModal* sm);

static void VISUAL_exit(VimModal* sm);

static void VISUAL_on_escape(VimModal* sm);


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void VimModal_ctor(VimModal* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void VimModal_start(VimModal* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: TransitionTo(normal)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `normal`.
            NORMAL_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void VimModal_dispatch_event(VimModal* sm, VimModal_EventId event_id)
{
    switch (sm->state_id)
    {
        // STATE: VimModal
        case VimModal_StateId_ROOT:
            // No events handled by this state (or its ancestors).
            break;
        
        // STATE: command
        case VimModal_StateId_COMMAND:
            switch (event_id)
            {
                case VimModal_EventId_ON_ESCAPE: COMMAND_on_escape(sm); break;
                case VimModal_EventId_ON_ENTER: COMMAND_on_enter(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: insert
        case VimModal_StateId_INSERT:
            switch (event_id)
            {
                case VimModal_EventId_ON_ESCAPE: INSERT_on_escape(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: normal
        case VimModal_StateId_NORMAL:
            switch (event_id)
            {
                case VimModal_EventId_ON_I: NORMAL_on_i(sm); break;
                case VimModal_EventId_ON_A: NORMAL_on_a(sm); break;
                case VimModal_EventId_ON_O: NORMAL_on_o(sm); break;
                case VimModal_EventId_ON_V: NORMAL_on_v(sm); break;
                case VimModal_EventId_ON_COLON: NORMAL_on_colon(sm); break;
                case VimModal_EventId_ON_SHIFT_R: NORMAL_on_shift_r(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: replace
        case VimModal_StateId_REPLACE:
            switch (event_id)
            {
                case VimModal_EventId_ON_ESCAPE: REPLACE_on_escape(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: visual
        case VimModal_StateId_VISUAL:
            switch (event_id)
            {
                case VimModal_EventId_ON_ESCAPE: VISUAL_on_escape(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
    }
    
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(VimModal* sm, VimModal_StateId desired_state)
{
    while (sm->state_id != desired_state)
    {
        switch (sm->state_id)
        {
            case VimModal_StateId_COMMAND: COMMAND_exit(sm); break;
            
            case VimModal_StateId_INSERT: INSERT_exit(sm); break;
            
            case VimModal_StateId_NORMAL: NORMAL_exit(sm); break;
            
            case VimModal_StateId_REPLACE: REPLACE_exit(sm); break;
            
            case VimModal_StateId_VISUAL: VISUAL_exit(sm); break;
            
            default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
        }
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(VimModal* sm)
{
    sm->state_id = VimModal_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state COMMAND
////////////////////////////////////////////////////////////////////////////////

static void COMMAND_enter(VimModal* sm)
{
    sm->state_id = VimModal_StateId_COMMAND;
}

static void COMMAND_exit(VimModal* sm)
{
    sm->state_id = VimModal_StateId_ROOT;
}

static void COMMAND_on_enter(VimModal* sm)
{
    // command behavior
    // uml: on_enter TransitionTo(normal)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        COMMAND_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `normal`.
        NORMAL_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for command
    
    // No ancestor handles this event.
}

static void COMMAND_on_escape(VimModal* sm)
{
    // command behavior
    // uml: on_escape TransitionTo(normal)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        COMMAND_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `normal`.
        NORMAL_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for command
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state INSERT
////////////////////////////////////////////////////////////////////////////////

static void INSERT_enter(VimModal* sm)
{
    sm->state_id = VimModal_StateId_INSERT;
}

static void INSERT_exit(VimModal* sm)
{
    sm->state_id = VimModal_StateId_ROOT;
}

static void INSERT_on_escape(VimModal* sm)
{
    // insert behavior
    // uml: on_escape TransitionTo(normal)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        INSERT_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `normal`.
        NORMAL_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for insert
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state NORMAL
////////////////////////////////////////////////////////////////////////////////

static void NORMAL_enter(VimModal* sm)
{
    sm->state_id = VimModal_StateId_NORMAL;
}

static void NORMAL_exit(VimModal* sm)
{
    sm->state_id = VimModal_StateId_ROOT;
}

static void NORMAL_on_a(VimModal* sm)
{
    // normal behavior
    // uml: on_a TransitionTo(insert)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        NORMAL_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `insert`.
        INSERT_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for normal
    
    // No ancestor handles this event.
}

static void NORMAL_on_colon(VimModal* sm)
{
    // normal behavior
    // uml: on_colon TransitionTo(command)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        NORMAL_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `command`.
        COMMAND_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for normal
    
    // No ancestor handles this event.
}

static void NORMAL_on_i(VimModal* sm)
{
    // normal behavior
    // uml: on_i TransitionTo(insert)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        NORMAL_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `insert`.
        INSERT_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for normal
    
    // No ancestor handles this event.
}

static void NORMAL_on_o(VimModal* sm)
{
    // normal behavior
    // uml: on_o TransitionTo(insert)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        NORMAL_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `insert`.
        INSERT_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for normal
    
    // No ancestor handles this event.
}

static void NORMAL_on_shift_r(VimModal* sm)
{
    // normal behavior
    // uml: on_shift_r TransitionTo(replace)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        NORMAL_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `replace`.
        REPLACE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for normal
    
    // No ancestor handles this event.
}

static void NORMAL_on_v(VimModal* sm)
{
    // normal behavior
    // uml: on_v TransitionTo(visual)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        NORMAL_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `visual`.
        VISUAL_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for normal
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state REPLACE
////////////////////////////////////////////////////////////////////////////////

static void REPLACE_enter(VimModal* sm)
{
    sm->state_id = VimModal_StateId_REPLACE;
}

static void REPLACE_exit(VimModal* sm)
{
    sm->state_id = VimModal_StateId_ROOT;
}

static void REPLACE_on_escape(VimModal* sm)
{
    // replace behavior
    // uml: on_escape TransitionTo(normal)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        REPLACE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `normal`.
        NORMAL_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for replace
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state VISUAL
////////////////////////////////////////////////////////////////////////////////

static void VISUAL_enter(VimModal* sm)
{
    sm->state_id = VimModal_StateId_VISUAL;
}

static void VISUAL_exit(VimModal* sm)
{
    sm->state_id = VimModal_StateId_ROOT;
}

static void VISUAL_on_escape(VimModal* sm)
{
    // visual behavior
    // uml: on_escape TransitionTo(normal)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        VISUAL_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `normal`.
        NORMAL_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for visual
    
    // No ancestor handles this event.
}

// Thread safe.
char const * VimModal_state_id_to_string(VimModal_StateId id)
{
    switch (id)
    {
        case VimModal_StateId_ROOT: return "ROOT";
        case VimModal_StateId_COMMAND: return "COMMAND";
        case VimModal_StateId_INSERT: return "INSERT";
        case VimModal_StateId_NORMAL: return "NORMAL";
        case VimModal_StateId_REPLACE: return "REPLACE";
        case VimModal_StateId_VISUAL: return "VISUAL";
        default: return "?";
    }
}

// Thread safe.
char const * VimModal_event_id_to_string(VimModal_EventId id)
{
    switch (id)
    {
        case VimModal_EventId_ON_A: return "ON_A";
        case VimModal_EventId_ON_COLON: return "ON_COLON";
        case VimModal_EventId_ON_ENTER: return "ON_ENTER";
        case VimModal_EventId_ON_ESCAPE: return "ON_ESCAPE";
        case VimModal_EventId_ON_I: return "ON_I";
        case VimModal_EventId_ON_O: return "ON_O";
        case VimModal_EventId_ON_SHIFT_R: return "ON_SHIFT_R";
        case VimModal_EventId_ON_V: return "ON_V";
        default: return "?";
    }
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif
