// Autogenerated with StateSmith 0.21.0-alpha-1+7e3f96c13426722a35ad6604c427da48d8538e48.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#pragma once  // You can also specify normal include guard. See https://github.com/StateSmith/StateSmith/blob/main/docs/settings.md
#include <stdint.h>

typedef enum Dyad_EventId
{
    Dyad_EventId_ON_OTHER_KEY = 0,
    Dyad_EventId_ON_PRIMARY_PRESS = 1,
    Dyad_EventId_ON_PRIMARY_RELEASE = 2,
    Dyad_EventId_ON_SECONDARY_MATCH = 3,
    Dyad_EventId_ON_SECONDARY_REPEAT = 4
} Dyad_EventId;

enum
{
    Dyad_EventIdCount = 5
};

typedef enum Dyad_StateId
{
    Dyad_StateId_ROOT = 0,
    Dyad_StateId_ARMED = 1,
    Dyad_StateId_IDLE = 2,
    Dyad_StateId_PRIMARY_HELD = 3
} Dyad_StateId;

enum
{
    Dyad_StateIdCount = 4
};


// Generated state machine
// forward declaration
typedef struct Dyad Dyad;

// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void Dyad_ctor(Dyad* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void Dyad_start(Dyad* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void Dyad_dispatch_event(Dyad* sm, Dyad_EventId event_id);

// Thread safe.
char const * Dyad_state_id_to_string(Dyad_StateId id);

// Thread safe.
char const * Dyad_event_id_to_string(Dyad_EventId id);

// Generated state machine
struct Dyad
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    Dyad_StateId state_id;
};

