// Autogenerated with StateSmith 0.21.0-alpha-1+7e3f96c13426722a35ad6604c427da48d8538e48.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#pragma once  // You can also specify normal include guard. See https://github.com/StateSmith/StateSmith/blob/main/docs/settings.md
#include <stdint.h>

typedef enum StickyCombo_EventId
{
    StickyCombo_EventId_ON_COMBO_PRESS = 0,
    StickyCombo_EventId_ON_RELEASE_BOTH = 1,
    StickyCombo_EventId_ON_RELEASE_KEY1 = 2,
    StickyCombo_EventId_ON_RELEASE_KEY2 = 3,
    StickyCombo_EventId_ON_TAP_KEY1 = 4,
    StickyCombo_EventId_ON_TAP_KEY2 = 5
} StickyCombo_EventId;

enum
{
    StickyCombo_EventIdCount = 6
};

typedef enum StickyCombo_StateId
{
    StickyCombo_StateId_ROOT = 0,
    StickyCombo_StateId_ARMED_BOTH = 1,
    StickyCombo_StateId_ARMED_FOR_KEY1 = 2,
    StickyCombo_StateId_ARMED_FOR_KEY2 = 3,
    StickyCombo_StateId_IDLE = 4
} StickyCombo_StateId;

enum
{
    StickyCombo_StateIdCount = 5
};


// Generated state machine
// forward declaration
typedef struct StickyCombo StickyCombo;

// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void StickyCombo_ctor(StickyCombo* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void StickyCombo_start(StickyCombo* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void StickyCombo_dispatch_event(StickyCombo* sm, StickyCombo_EventId event_id);

// Thread safe.
char const * StickyCombo_state_id_to_string(StickyCombo_StateId id);

// Thread safe.
char const * StickyCombo_event_id_to_string(StickyCombo_EventId id);

// Generated state machine
struct StickyCombo
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    StickyCombo_StateId state_id;
};

